spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shop
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shop
    username: root
    password: 3419
