management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health
      health:
        show-details: always

toss:
  payments:
    enabled: true
    client_key: ${TOSS_CLIENT_KEY}
    secret_key: ${TOSS_SECRET_KEY}
    fail_url: http://localhost:8080/api/v1/order/fail
    success_url: http://localhost:8080/api/v1/order/success
    basic_url: https://api.tosspayments.com/v1/payments/

spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.MariaDBDialect
    properties:
      logging:
        level:
          org.hibernate.SQL: debug
          org.hibernate.orm.jdbc.bind: trace
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_qD0HzA3fK/.well-known/jwks.json

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: ${AMAZON_S3_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cognito:
      pool-id: ${COGNITO_POOL_ID}
      client-id: ${COGNITO_CLIENT_ID}



#    logging:
#      level:
#        org:
#          springframework:
#            data:
#              elasticsearch:
#                client:
#                  WIRE=TRACE:TRACE
#
