spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shop
    username: root
    password: 3419

#  Debug
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true