spring:
  #DB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/shop
    username: root
    password: 3419

#  autoconfigure:
#    exclude:
#      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
#      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
#      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration


  #  Debug
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# elastic_search
elasticsearch:
  server:
    url: https://localhost:9200  # Elasticsearch 서버 URL
  api:
    key: bEZzVWZZMEJNTTMwN1RaT2hEbC06ZGtYTHUxcE1UTnVMN1VwX2IweFJYUQ== # Elasticsearch 서버 api key

#toss
toss:
  payments:
    enabled: true
    client_key: test_ck_vZnjEJeQVxb5mJnxvmRD8PmOoBN0
    secret_key: test_sk_QbgMGZzorzw0PjK0GBMk8l5E1em4
    fail_url: http://localhost:8080/api/v1/payment/fail
    success_url: http://localhost:8080/api/v1/payment/success
    basic_url: https://api.tosspayments.com/v1/payments/

#api json타입 사용
springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui: #swagger 사용
    path: /swagger-ui.html


# AWS S3
#cloud:
#  aws:
#    credentials:
#      accessKey: AKIAQEUG5GLYJB6LVDTX
#      secretKey: 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
#    s3:
#      bucket: amzamll.temp
#      region:
#        static: ap-northeast-2
#    stack:
#      auto : false

cloud:
  aws:
    credentials:
      accessKey: AKIAQEUG5GLYJB6LVDTX
      secretKey: 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
    s3:
      bucket: amzamll.temp
    region:
      static: ap-northeast-2
    stack:
      auto: false

#    logging:
#      level:
#        org:
#          springframework:
#            data:
#              elasticsearch:
#                client:
#                  WIRE=TRACE:TRACE
#
