name: Java CI/CD with Gradle

on:
  pull_request:
    branches: [ "develop" ]
  push:
    branches: [ "develop" ]

jobs:
  build-and-push-image:
    ## checkout후 자바 17 버전으로 설정을 합니다
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      ## gradlew 의 권한을 줍니다.
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
       
      ## gradle build
      - name: Build with Gradle
        run: ./gradlew clean build --debug
     ## 이미지 태그에 시간 설정을 하기위해서 현재 시간(current-time)을 가져옵니다. 이후 이를 steps.current-time.outputs.formattedTime로 사용합니다.  
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DDTHH-mm-ss
          utcOffset: "+09:00"
      
      # 현재 시간을 출력
      - name: Show Current Time
        run: echo "CurrentTime=${{steps.current-time.outputs.formattedTime}}"

      # 현재 시간을 파일에 기록
      - name: Save current time to a file
        run: echo ${{steps.current-time.outputs.formattedTime}} > current-time.txt

      # 아티팩트로 현재 시간 파일 업로드
      - name: Upload current time as artifact
        uses: actions/upload-artifact@v2
        with:
          name: current-time
          path: current-time.txt

      ## AWS에 로그인합니다. aws-region은 서울로 설정(ap-northeast-2)했습니다
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          
      ## ECR에 로그인합니다
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      ## 앞의 스탭에서 ${{steps.current-time.outputs.formattedTime}}로 현재 시간을 가져옵니다.
      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t sample:${{steps.current-time.outputs.formattedTime}} .
          docker tag sample:${{steps.current-time.outputs.formattedTime}} 009946608368.dkr.ecr.ap-northeast-2.amazonaws.com/amzdraw-dev:${{steps.current-time.outputs.formattedTime}}
          docker push 009946608368.dkr.ecr.ap-northeast-2.amazonaws.com/amzdraw-dev:${{steps.current-time.outputs.formattedTime}}

#  # CD 수행 부분
#  update-helm-chart:
#    needs: build-and-push-image
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#        with:
#          repository: 'AWS-Cloud-3rd-Project/AMZMall_Dev_GitOps'
#          token: ${{ secrets.AMZMALL_DEV_GITOPS_REPO_TOKEN }}
#
#      # 아티팩트 다운로드
#      - name: Download current time artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: current-time
#          path: artifact
#
#      # 아티팩트에서 현재 시간 읽기
#      - name: Read current time from artifact
#        id: read-time
#        run: echo "IMAGE_TAG=$(cat artifact/current-time.txt)" >> $GITHUB_ENV
#
#
#      # 헬름 차트 수정
#      - name: Update Helm chart values
#        run: |
#          sed -i "s/tag: .*/tag: ${{ env.IMAGE_TAG }}/" ./values.yaml
#
#      # 변경 사항 커밋 및 푸쉬
#      - name: Commit and push changes
#        run: |
#          git config --global user.email "ehgud9912@naver.com"
#          git config --global user.name "dhkim1206"
#          git add values.yaml
#          git commit -m "Update image tag to latest"
#          git push
